<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />


<meta name="date" content="2025-08-31" />

<title>Power Analysis for Latent Variable Mediation</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">

div.csl-bib-body { }
div.csl-entry {
clear: both;
margin-bottom: 0em;
}
.hanging div.csl-entry {
margin-left:2em;
text-indent:-2em;
}
div.csl-left-margin {
min-width:2em;
float:left;
}
div.csl-right-inline {
margin-left:2em;
padding-left:1em;
}
div.csl-indent {
margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Power Analysis for Latent Variable
Mediation</h1>
<h4 class="date">2025-08-31</h4>



<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This article is a brief illustration of how to use
<code>power4test()</code> from the package <a href="https://sfcheung.github.io/power4mome/">power4mome</a> to do power
analysis for the mediation effect among latent factors in a model to be
fitted by structural equation model modeling using
<code>lavaan</code>.</p>
</div>
<div id="prerequisite" class="section level1">
<h1>Prerequisite</h1>
<p>Basic knowledge about fitting models by <code>lavaan</code> is
required. Readers are also expected to have basic knowledge of mediation
and structural equation modeling.</p>
</div>
<div id="scope" class="section level1">
<h1>Scope</h1>
<p>To make this vignette self-contained, some sections from
<code>vignette(&quot;power4mome&quot;)</code> are repeated here.</p>
<p>To do power analysis for a mediation effect in a path model with no
latent factors, please refer to <code>vignette(&quot;power4mome&quot;)</code>.</p>
</div>
<div id="package" class="section level1">
<h1>Package</h1>
<p>This introduction only needs the following package:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(power4mome)</span></code></pre></div>
</div>
<div id="workflow" class="section level1">
<h1>Workflow</h1>
<p>Two functions are sufficient for estimating power given a model,
population values, sample size, and the test to be used. This is the
workflow:</p>
<ol style="list-style-type: decimal">
<li><p>Specify the model syntax for the population model, in
<code>lavaan</code> style, and set the population values of the model
parameters.</p></li>
<li><p>Call <code>power4test()</code> to examine the setup and the
datasets generated. Repeat this and previous steps until the model is
specified correctly.</p></li>
<li><p>Call <code>power4test()</code> again, with the test to do
specified.</p></li>
<li><p>Call <code>rejection_rates()</code> to compute the
power.</p></li>
</ol>
</div>
<div id="mediation" class="section level1">
<h1>Mediation</h1>
<p>Let’s consider a simple mediation model with three factors. We would
like to estimate the power of testing the mediation effect by Monte
Carlo confidence interval.</p>
<div id="specify-the-population-model" class="section level2">
<h2>Specify the Population Model</h2>
<p>For a model with latent factor, we only need to specify the model
syntax for the <em>factors</em>. No need to include the measurement part
and the indicators.</p>
<p>This is the model syntax:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a><span class="st">fm ~ fx</span></span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a><span class="st">fy ~ fm + fx</span></span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a><span class="st">&quot;</span></span></code></pre></div>
<p>The latent variables are <code>fx</code>, <code>fm</code>, and
<code>fy</code>. There is an indirect path from <code>fx</code> to
<code>fy</code>, through <code>fm</code>.</p>
<p>Note that, even if we are going to test a mediation effect, we do not
need to add any labels to this model. This will be taken care of by the
test functions, through the use of the package <a href="https://sfcheung.github.io/manymome/"><code>manymome</code></a>
<span class="citation">(Cheung &amp; Cheung, 2024)</span>.</p>
</div>
<div id="es_convention" class="section level2">
<h2>Specify The Population Values</h2>
<p>There are two approaches to do this:</p>
<ul>
<li><p>Using named vectors or lists.</p></li>
<li><p>Using a multiline string similar to <code>lavaan</code> model
syntax.</p></li>
</ul>
<p>The second approach is demonstrated below.</p>
<p>Suppose we want to estimate the power when:</p>
<ul>
<li><p>The path from <code>fx</code> to <code>fm</code> are “large” in
strength.</p></li>
<li><p>The path from <code>fm</code> to <code>fy</code> are “large” in
strength.</p></li>
<li><p>The path from <code>fx</code> to <code>fm</code> are “small” in
strength.</p></li>
</ul>
<p>By default, <code>power4mome</code> use this convention for
regression path and correlation:<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<ul>
<li><p>Small: .10 (or -.10)</p></li>
<li><p>Medium: .30 (or -.30)</p></li>
<li><p>Large: .50 (or -.50)</p></li>
</ul>
<p>All these values are for the standardized solution (the correlations
and so-called “betas”).</p>
<p>The following string denotes the desired values:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>mod_es <span class="ot">&lt;-</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a><span class="st">fm ~ fx: l</span></span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a><span class="st">fy ~ fm: l</span></span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a><span class="st">fy ~ fx: s</span></span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a><span class="st">&quot;</span></span></code></pre></div>
<p>Each line starts with a <em>tag</em>, which is the parameter
presented in <code>lavaan</code> syntax. The tag ends with a colon,
<code>:</code>.</p>
<p>After the colon is <em>population value</em>, which can be:</p>
<ul>
<li><p>A string denoting the value. By default:</p>
<ul>
<li><p><code>s</code>: Small. (<code>-s</code> for small and
negative.)</p></li>
<li><p><code>m</code>: Medium. (<code>-m</code> for medium and
negative.)</p></li>
<li><p><code>l</code>: Large. (<code>-l</code> for large and
negative.)</p></li>
<li><p><code>nil</code>: Zero.</p></li>
</ul></li>
</ul>
<p>All other regression coefficients and covariances, if not specified
in this string, are set to zero.</p>
</div>
<div id="measurement" class="section level2">
<h2>Specify the Measurement Part</h2>
<p>Power analysis is usually conducted before data collection. We rarely
know in advance the factor loadings of all items. For the purpose of
power analysis, which is not intended to be conducted with the knowledge
of all factor loadings, we believe that, instead of specifying all the
loadings, it is sufficient to specify two values for each factor:</p>
<ul>
<li><p>The number of indicators.</p></li>
<li><p>The population reliability.</p></li>
</ul>
<p>This is the approach used in <code>power4mome</code>.</p>
<p>For each factor, the population standardized factor loadings for each
indicator will be derived automatically from the hypothesized (or
expected) population reliability and the number of indicators, assuming
that all indicators have equal loadings.</p>
<p>Although the equal-loading assumption is unrealistic, in <em>a
priori</em> power analysis, it is difficult, if not impossible, to
specify the pattern of factor loadings. This level of details is also
not necessary because the power estimated is merely used to guide the
planning of data collection, instead of estimating the “true” power
after data is collected.</p>
<p>Two arguments will be used to set the number of indicators and the
reliability.</p>
<ul>
<li><p><code>number_of_indicators</code>: This should be a
<em>named</em> vector of the number of indicators for each factor. The
names are the names of the factors as appeared in the model syntax, and
the values are the number of indicators.</p></li>
<li><p><code>reliability</code>: This should be a <em>named</em> vector
of the reliability for each factor. The names are the names of the
factors as appeared in the model syntax, and the values are population
reliability.</p></li>
</ul>
<p>For example, suppose we will use the following vectors:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">fm =</span> <span class="dv">3</span>,</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>       <span class="at">fx =</span> <span class="dv">4</span>,</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>       <span class="at">fy =</span> <span class="dv">5</span>)</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>mod_rel <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">fy =</span> .<span class="dv">70</span>,</span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>             <span class="at">fm =</span> .<span class="dv">60</span>,</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>             <span class="at">fx =</span> .<span class="dv">50</span>)</span></code></pre></div>
<p>The numbers of indicators for <code>fx</code>, <code>fm</code>, and
<code>fy</code> are 4, 3, and 5, respectively.</p>
<p>The population reliability coefficients for <code>fx</code>,
<code>fm</code>, and <code>fy</code> are .50, .60, and .70,
respectively. In real research, reliability as low as .50 can be
problematic. We chose these values merely for illustration</p>
<p>The orders are intentionally arbitrary, to demonstrate the order does
not matter. The names will be used to interpret the numbers
correctly.</p>
</div>
<div id="call-power4test-to-check-the-model" class="section level2">
<h2>Call <code>power4test()</code> to Check the Model</h2>
<p>We are all set and can call <code>power4test()</code> to check the
model:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">power4test</span>(<span class="at">nrep =</span> <span class="dv">2</span>,</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>                  <span class="at">model =</span> mod,</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>                  <span class="at">pop_es =</span> mod_es,</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>                  <span class="at">number_of_indicators =</span> k,</span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>                  <span class="at">reliability =</span> mod_rel,</span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>                  <span class="at">n =</span> <span class="dv">50000</span>,</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>                  <span class="at">iseed =</span> <span class="dv">1234</span>)</span></code></pre></div>
<p>These are the arguments used:</p>
<ul>
<li><p><code>nrep</code>: The number of replications. In this stage, a
small number can be used. It is more important to have a large sample
size than to have many replications.</p></li>
<li><p><code>model</code>: The model syntax.</p></li>
<li><p><code>pop_es</code>: The string setting the population
values.</p></li>
<li><p><code>number_of_indicators</code>: A named vector of the number
of indicators for each factor, described in the previous
section.</p></li>
<li><p><code>reliability</code>: A named vector of the population
reliability for each factor, described in the previous section.</p></li>
<li><p><code>n</code>: The sample size in each replications. In this
stage, just for checking the model and the data generation, this number
can be set to a large one unless the model is slow to fit when the
sample size is large.</p></li>
<li><p><code>iseed</code>: If supplied, it is used to set the seed for
the random number generator. It is advised to always set this to an
arbitrary integer, to make the results reproducible.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p></li>
</ul>
<p>The population values can be shown by printing this object:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a>out</span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a><span class="co">#&gt; ====================== Model Information ======================</span></span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a><span class="co">#&gt; == Model on Factors/Variables ==</span></span>
<span id="cb7-6"><a href="#cb7-6" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-7"><a href="#cb7-7" tabindex="-1"></a><span class="co">#&gt; fm ~ fx</span></span>
<span id="cb7-8"><a href="#cb7-8" tabindex="-1"></a><span class="co">#&gt; fy ~ fm + fx</span></span>
<span id="cb7-9"><a href="#cb7-9" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-10"><a href="#cb7-10" tabindex="-1"></a><span class="co">#&gt; == Model on Variables/Indicators ==</span></span>
<span id="cb7-11"><a href="#cb7-11" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-12"><a href="#cb7-12" tabindex="-1"></a><span class="co">#&gt; fm ~ fx</span></span>
<span id="cb7-13"><a href="#cb7-13" tabindex="-1"></a><span class="co">#&gt; fy ~ fm + fx</span></span>
<span id="cb7-14"><a href="#cb7-14" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-15"><a href="#cb7-15" tabindex="-1"></a><span class="co">#&gt; fm =~ fm1 + fm2 + fm3</span></span>
<span id="cb7-16"><a href="#cb7-16" tabindex="-1"></a><span class="co">#&gt; fx =~ fx1 + fx2 + fx3 + fx4</span></span>
<span id="cb7-17"><a href="#cb7-17" tabindex="-1"></a><span class="co">#&gt; fy =~ fy1 + fy2 + fy3 + fy4 + fy5</span></span>
<span id="cb7-18"><a href="#cb7-18" tabindex="-1"></a><span class="co">#&gt; ====== Population Values ======</span></span>
<span id="cb7-19"><a href="#cb7-19" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-20"><a href="#cb7-20" tabindex="-1"></a><span class="co">#&gt; Regressions:</span></span>
<span id="cb7-21"><a href="#cb7-21" tabindex="-1"></a><span class="co">#&gt;                    Population</span></span>
<span id="cb7-22"><a href="#cb7-22" tabindex="-1"></a><span class="co">#&gt;   fm ~                       </span></span>
<span id="cb7-23"><a href="#cb7-23" tabindex="-1"></a><span class="co">#&gt;     fx                0.500  </span></span>
<span id="cb7-24"><a href="#cb7-24" tabindex="-1"></a><span class="co">#&gt;   fy ~                       </span></span>
<span id="cb7-25"><a href="#cb7-25" tabindex="-1"></a><span class="co">#&gt;     fm                0.500  </span></span>
<span id="cb7-26"><a href="#cb7-26" tabindex="-1"></a><span class="co">#&gt;     fx                0.100  </span></span>
<span id="cb7-27"><a href="#cb7-27" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-28"><a href="#cb7-28" tabindex="-1"></a><span class="co">#&gt; Variances:</span></span>
<span id="cb7-29"><a href="#cb7-29" tabindex="-1"></a><span class="co">#&gt;                    Population</span></span>
<span id="cb7-30"><a href="#cb7-30" tabindex="-1"></a><span class="co">#&gt;    .fm                0.750  </span></span>
<span id="cb7-31"><a href="#cb7-31" tabindex="-1"></a><span class="co">#&gt;    .fy                0.690  </span></span>
<span id="cb7-32"><a href="#cb7-32" tabindex="-1"></a><span class="co">#&gt;     fx                1.000  </span></span>
<span id="cb7-33"><a href="#cb7-33" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-34"><a href="#cb7-34" tabindex="-1"></a><span class="co">#&gt; (Computing indirect effects for 2 paths ...)</span></span>
<span id="cb7-35"><a href="#cb7-35" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-36"><a href="#cb7-36" tabindex="-1"></a><span class="co">#&gt; == Population Conditional/Indirect Effect(s) ==</span></span>
<span id="cb7-37"><a href="#cb7-37" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-38"><a href="#cb7-38" tabindex="-1"></a><span class="co">#&gt; == Indirect Effect(s) ==</span></span>
<span id="cb7-39"><a href="#cb7-39" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-40"><a href="#cb7-40" tabindex="-1"></a><span class="co">#&gt;                  ind</span></span>
<span id="cb7-41"><a href="#cb7-41" tabindex="-1"></a><span class="co">#&gt; fx -&gt; fm -&gt; fy 0.250</span></span>
<span id="cb7-42"><a href="#cb7-42" tabindex="-1"></a><span class="co">#&gt; fx -&gt; fy       0.100</span></span>
<span id="cb7-43"><a href="#cb7-43" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-44"><a href="#cb7-44" tabindex="-1"></a><span class="co">#&gt;  - The &#39;ind&#39; column shows the indirect effect(s).</span></span>
<span id="cb7-45"><a href="#cb7-45" tabindex="-1"></a><span class="co">#&gt;  </span></span>
<span id="cb7-46"><a href="#cb7-46" tabindex="-1"></a><span class="co">#&gt; ==== Population Reliability ====</span></span>
<span id="cb7-47"><a href="#cb7-47" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-48"><a href="#cb7-48" tabindex="-1"></a><span class="co">#&gt;   fy  fm  fx</span></span>
<span id="cb7-49"><a href="#cb7-49" tabindex="-1"></a><span class="co">#&gt;  0.7 0.6 0.5</span></span>
<span id="cb7-50"><a href="#cb7-50" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-51"><a href="#cb7-51" tabindex="-1"></a><span class="co">#&gt; == Population Standardized Loadings ==</span></span>
<span id="cb7-52"><a href="#cb7-52" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-53"><a href="#cb7-53" tabindex="-1"></a><span class="co">#&gt;     fm    fx    fy</span></span>
<span id="cb7-54"><a href="#cb7-54" tabindex="-1"></a><span class="co">#&gt;  0.661 0.522 0.408</span></span>
<span id="cb7-55"><a href="#cb7-55" tabindex="-1"></a><span class="co">#&gt; ======================= Data Information =======================</span></span>
<span id="cb7-56"><a href="#cb7-56" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-57"><a href="#cb7-57" tabindex="-1"></a><span class="co">#&gt; Number of Replications:  2 </span></span>
<span id="cb7-58"><a href="#cb7-58" tabindex="-1"></a><span class="co">#&gt; Sample Sizes:  50000 </span></span>
<span id="cb7-59"><a href="#cb7-59" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-60"><a href="#cb7-60" tabindex="-1"></a><span class="co">#&gt; Call print with &#39;data_long = TRUE&#39; for further information.</span></span>
<span id="cb7-61"><a href="#cb7-61" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-62"><a href="#cb7-62" tabindex="-1"></a><span class="co">#&gt; ==================== Extra Element(s) Found ====================</span></span>
<span id="cb7-63"><a href="#cb7-63" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-64"><a href="#cb7-64" tabindex="-1"></a><span class="co">#&gt; - fit</span></span>
<span id="cb7-65"><a href="#cb7-65" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-66"><a href="#cb7-66" tabindex="-1"></a><span class="co">#&gt; === Element(s) of the First Dataset ===</span></span>
<span id="cb7-67"><a href="#cb7-67" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-68"><a href="#cb7-68" tabindex="-1"></a><span class="co">#&gt; ============ &lt;fit&gt; ============</span></span>
<span id="cb7-69"><a href="#cb7-69" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-70"><a href="#cb7-70" tabindex="-1"></a><span class="co">#&gt; lavaan 0.6-19 ended normally after 44 iterations</span></span>
<span id="cb7-71"><a href="#cb7-71" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-72"><a href="#cb7-72" tabindex="-1"></a><span class="co">#&gt;   Estimator                                         ML</span></span>
<span id="cb7-73"><a href="#cb7-73" tabindex="-1"></a><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span id="cb7-74"><a href="#cb7-74" tabindex="-1"></a><span class="co">#&gt;   Number of model parameters                        27</span></span>
<span id="cb7-75"><a href="#cb7-75" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-76"><a href="#cb7-76" tabindex="-1"></a><span class="co">#&gt;   Number of observations                         50000</span></span>
<span id="cb7-77"><a href="#cb7-77" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-78"><a href="#cb7-78" tabindex="-1"></a><span class="co">#&gt; Model Test User Model:</span></span>
<span id="cb7-79"><a href="#cb7-79" tabindex="-1"></a><span class="co">#&gt;                                                       </span></span>
<span id="cb7-80"><a href="#cb7-80" tabindex="-1"></a><span class="co">#&gt;   Test statistic                                38.042</span></span>
<span id="cb7-81"><a href="#cb7-81" tabindex="-1"></a><span class="co">#&gt;   Degrees of freedom                                51</span></span>
<span id="cb7-82"><a href="#cb7-82" tabindex="-1"></a><span class="co">#&gt;   P-value (Chi-square)                           0.910</span></span></code></pre></div>
<p>By the default, the population model will be fitted to each dataset,
hence the section <code>&lt;fit&gt;</code>. The fit is not “perfect”
because the model is not a saturated model. However, the
<em>p</em>-value is high and not significant (because, with the
population model fitted, the chance of significant is close to .05).</p>
<p>Although we specify only the structure for the latent factors, we can
see the automatically generated measurement part syntax in the section
<code>Model on Variables/Indicators</code>:</p>
<pre><code>#&gt; fm =~ fm1 + fm2 + fm3
#&gt; fx =~ fx1 + fx2 + fx3 + fx4
#&gt; fy =~ fy1 + fy2 + fy3 + fy4 + fy5</code></pre>
<p>It confirmed that we specified the measurement part correctly.</p>
<p>We then check the section <code>Population Values</code> to see
whether the values are what we expected.</p>
<ul>
<li>In this example, the population values for the regression paths are
what we specified.</li>
</ul>
<p>If they are different from what we expect, check the string for
<code>pop_es</code> to see whether we set the population values
correctly.</p>
<ul>
<li>The section <code>Variances:</code> shows the variances or
<em>error</em> variances of the latent factors. Because <code>fm</code>
and <code>fy</code> are endogenous factors, the values presented, next
to <code>.fm</code> and <code>.fy</code>, are error variances, and
that’s why they are not 1, unlike <code>fx</code>.</li>
</ul>
<p>The section <code>Population Reliability</code> shows the population
reliability coefficients:</p>
<pre><code>#&gt; ==== Population Reliability ====
#&gt; 
#&gt;   fy  fm  fx
#&gt;  0.7 0.6 0.5</code></pre>
<p>They are the values we set to <code>reliability</code>.</p>
<p>The section <code>Population Standardized Loadings</code> shows the
standardized factor loadings for each factor. Only one value for each
factor because the loadings are assumed to be the same for all
items:</p>
<pre><code>#&gt; == Population Standardized Loadings ==
#&gt; 
#&gt;     fm    fx    fy
#&gt;  0.661 0.522 0.408</code></pre>
<p>If necessary, we can check the data generation by adding
<code>data_long = TRUE</code> when printing the output:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">print</span>(out,</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>      <span class="at">data_long =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Two new sections will be printed. This is the first one:</p>
<pre><code>#&gt; ==== Descriptive Statistics ====
#&gt; 
#&gt;     vars     n mean   sd  skew kurtosis se
#&gt; fm1    1 1e+05 0.00 1.00  0.01     0.00  0
#&gt; fm2    2 1e+05 0.01 1.00  0.01    -0.01  0
#&gt; fm3    3 1e+05 0.00 1.01  0.00    -0.02  0
#&gt; fx1    4 1e+05 0.00 1.00  0.00     0.00  0
#&gt; fx2    5 1e+05 0.00 1.00 -0.01     0.00  0
#&gt; fx3    6 1e+05 0.00 1.00 -0.01    -0.02  0
#&gt; fx4    7 1e+05 0.00 1.00  0.00     0.00  0
#&gt; fy1    8 1e+05 0.00 1.00  0.01     0.01  0
#&gt; fy2    9 1e+05 0.00 1.00  0.01     0.00  0
#&gt; fy3   10 1e+05 0.00 1.00  0.00     0.01  0
#&gt; fy4   11 1e+05 0.01 1.00  0.01     0.00  0
#&gt; fy5   12 1e+05 0.00 1.00  0.02    -0.01  0</code></pre>
<p>The section <code>Descriptive Statistics</code>, generated by
<code>psych::describe()</code>, shows basic descriptive statistics for
indicators. As expected, they have means close to zero and standard
deviations close to one, because the datasets were generated using the
standardized model.</p>
<p>This is the second one:</p>
<pre><code>#&gt; fy5   12 1e+05 0.00 1.00  0.02    -0.01  0
#&gt; 
#&gt; ===== Parameter Estimates Based on All 2 Samples Combined =====
#&gt; 
#&gt; Total Sample Size: 100000 
#&gt; 
#&gt; ==== Standardized Estimates ====
#&gt; 
#&gt; Variances and error variances omitted.
#&gt; 
#&gt; Latent Variables:
#&gt;                     est.std
#&gt;   fm =~                    
#&gt;     fm1               0.578
#&gt;     fm2               0.579
#&gt;     fm3               0.578
#&gt;   fx =~                    
#&gt;     fx1               0.445
#&gt;     fx2               0.443
#&gt;     fx3               0.445
#&gt;     fx4               0.445
#&gt;   fy =~                    
#&gt;     fy1               0.559
#&gt;     fy2               0.560
#&gt;     fy3               0.563
#&gt;     fy4               0.565
#&gt;     fy5               0.569
#&gt; 
#&gt; Regressions:
#&gt;                     est.std
#&gt;   fm ~                     
#&gt;     fx                0.504
#&gt;   fy ~                     
#&gt;     fm                0.505
#&gt;     fx                0.097</code></pre>
<p>The section <code>Parameter Estimates Based on</code> shows the
parameter estimates when the <em>population model</em> is fitted to
<em>all the datasets combined</em>. When the total sample size is large,
these estimates should be close to the population values.</p>
<p>The results show that we have specified the population model
correctly. We can proceed to specify the test and estimate the
power.</p>
</div>
<div id="med_power" class="section level2">
<h2>Call <code>power4test()</code> to Do the Target Test</h2>
<p>We can now do the simulation to estimate power. A large number of
datasets (e.g., 400) of the target sample size are to be generated, and
then the target test will be conducted in each of these datasets.</p>
<p>Suppose we would like to estimate the power of using Monte Carlo
confidence interval to test the indirect effect from <code>fx</code> to
<code>fy</code> through <code>fm</code>, when sample size is 150. This
is the call:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">power4test</span>(<span class="at">nrep =</span> <span class="dv">400</span>,</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>                  <span class="at">model =</span> mod,</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>                  <span class="at">pop_es =</span> mod_es,</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>                  <span class="at">number_of_indicators =</span> k,</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>                  <span class="at">reliability =</span> mod_rel,</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>                  <span class="at">n =</span> <span class="dv">150</span>,</span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>                  <span class="at">R =</span> <span class="dv">2000</span>,</span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>                  <span class="at">ci_type =</span> <span class="st">&quot;mc&quot;</span>,</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>                  <span class="at">test_fun =</span> test_indirect_effect,</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>                  <span class="at">test_args =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">&quot;fx&quot;</span>,</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>                                   <span class="at">m =</span> <span class="st">&quot;fm&quot;</span>,</span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>                                   <span class="at">y =</span> <span class="st">&quot;fy&quot;</span>,</span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>                                   <span class="at">mc_ci =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-14"><a href="#cb14-14" tabindex="-1"></a>                  <span class="at">iseed =</span> <span class="dv">1234</span>,</span>
<span id="cb14-15"><a href="#cb14-15" tabindex="-1"></a>                  <span class="at">parallel =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>These are the new arguments used:</p>
<ul>
<li><p><code>R</code>: The number of replications used to generate the
Monte Carlo simulated estimates, 2000 in this example. In real studies,
this number should be 10000 or even 20000 for Monte Carlo confidence
intervals. However, 2000 is sufficient because the goal is to estimate
power by generating many intervals, rather than to have one single
stable interval.</p></li>
<li><p><code>ci_type</code>: The method used to generate estimates.
Support both Monte Carlo (<code>&quot;mc&quot;</code>) and nonparametric
bootstrapping (<code>&quot;boot&quot;</code>).<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> Although bootstrapping is usually used to
test an indirect effect, it is very slow to do <code>R</code>
bootstrapping in <code>nrep</code> datasets (the model will be fitted
<code>R * nrep</code> times). Therefore, it is preferable to use Monte
Carlo to do the initial estimation.</p></li>
<li><p><code>test_fun</code>: The function to be used to do the test for
each replication. Any function following a specific requirement can be
used, and <code>power4mome</code> comes with several built-in functions
for some common tests. The function <code>test_indirect_effect()</code>
is used to test an indirect effect in the model.</p></li>
<li><p><code>test_args</code>: A named list of arguments to be supplied
to <code>test_fun</code>. For <code>test_indirect_effect()</code>, it is
a named list specifying the predictor (<code>x</code>), the mediator(s)
(<code>m</code>), and the outcome (<code>y</code>). A path with any
number of mediators can be supported. Please refer to the help page of
<code>test_indirect_effect()</code>.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p></li>
<li><p><code>parallel</code>: If the test to be conducted is slow, which
is the case for tests done by Monte Carlo or nonparametric bootstrapping
confidence interval, it is advised to enable parallel processing by
setting <code>parallel</code> to <code>TRUE</code>.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p></li>
</ul>
<p>For <code>nrep = 400</code>, the 95% confidence limits for a power of
.80 are about .04 below and above .80. This should be precise enough for
determining whether a sample size has sufficient power.</p>
<p>This is the default printout:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>out</span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a><span class="co">#&gt; ====================== Model Information ======================</span></span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-5"><a href="#cb15-5" tabindex="-1"></a><span class="co">#&gt; == Model on Factors/Variables ==</span></span>
<span id="cb15-6"><a href="#cb15-6" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-7"><a href="#cb15-7" tabindex="-1"></a><span class="co">#&gt; fm ~ fx</span></span>
<span id="cb15-8"><a href="#cb15-8" tabindex="-1"></a><span class="co">#&gt; fy ~ fm + fx</span></span>
<span id="cb15-9"><a href="#cb15-9" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-10"><a href="#cb15-10" tabindex="-1"></a><span class="co">#&gt; == Model on Variables/Indicators ==</span></span>
<span id="cb15-11"><a href="#cb15-11" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-12"><a href="#cb15-12" tabindex="-1"></a><span class="co">#&gt; fm ~ fx</span></span>
<span id="cb15-13"><a href="#cb15-13" tabindex="-1"></a><span class="co">#&gt; fy ~ fm + fx</span></span>
<span id="cb15-14"><a href="#cb15-14" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-15"><a href="#cb15-15" tabindex="-1"></a><span class="co">#&gt; fm =~ fm1 + fm2 + fm3</span></span>
<span id="cb15-16"><a href="#cb15-16" tabindex="-1"></a><span class="co">#&gt; fx =~ fx1 + fx2 + fx3 + fx4</span></span>
<span id="cb15-17"><a href="#cb15-17" tabindex="-1"></a><span class="co">#&gt; fy =~ fy1 + fy2 + fy3 + fy4 + fy5</span></span>
<span id="cb15-18"><a href="#cb15-18" tabindex="-1"></a><span class="co">#&gt; ====== Population Values ======</span></span>
<span id="cb15-19"><a href="#cb15-19" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-20"><a href="#cb15-20" tabindex="-1"></a><span class="co">#&gt; Regressions:</span></span>
<span id="cb15-21"><a href="#cb15-21" tabindex="-1"></a><span class="co">#&gt;                    Population</span></span>
<span id="cb15-22"><a href="#cb15-22" tabindex="-1"></a><span class="co">#&gt;   fm ~                       </span></span>
<span id="cb15-23"><a href="#cb15-23" tabindex="-1"></a><span class="co">#&gt;     fx                0.500  </span></span>
<span id="cb15-24"><a href="#cb15-24" tabindex="-1"></a><span class="co">#&gt;   fy ~                       </span></span>
<span id="cb15-25"><a href="#cb15-25" tabindex="-1"></a><span class="co">#&gt;     fm                0.500  </span></span>
<span id="cb15-26"><a href="#cb15-26" tabindex="-1"></a><span class="co">#&gt;     fx                0.100  </span></span>
<span id="cb15-27"><a href="#cb15-27" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-28"><a href="#cb15-28" tabindex="-1"></a><span class="co">#&gt; Variances:</span></span>
<span id="cb15-29"><a href="#cb15-29" tabindex="-1"></a><span class="co">#&gt;                    Population</span></span>
<span id="cb15-30"><a href="#cb15-30" tabindex="-1"></a><span class="co">#&gt;    .fm                0.750  </span></span>
<span id="cb15-31"><a href="#cb15-31" tabindex="-1"></a><span class="co">#&gt;    .fy                0.690  </span></span>
<span id="cb15-32"><a href="#cb15-32" tabindex="-1"></a><span class="co">#&gt;     fx                1.000  </span></span>
<span id="cb15-33"><a href="#cb15-33" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-34"><a href="#cb15-34" tabindex="-1"></a><span class="co">#&gt; (Computing indirect effects for 2 paths ...)</span></span>
<span id="cb15-35"><a href="#cb15-35" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-36"><a href="#cb15-36" tabindex="-1"></a><span class="co">#&gt; == Population Conditional/Indirect Effect(s) ==</span></span>
<span id="cb15-37"><a href="#cb15-37" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-38"><a href="#cb15-38" tabindex="-1"></a><span class="co">#&gt; == Indirect Effect(s) ==</span></span>
<span id="cb15-39"><a href="#cb15-39" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-40"><a href="#cb15-40" tabindex="-1"></a><span class="co">#&gt;                  ind</span></span>
<span id="cb15-41"><a href="#cb15-41" tabindex="-1"></a><span class="co">#&gt; fx -&gt; fm -&gt; fy 0.250</span></span>
<span id="cb15-42"><a href="#cb15-42" tabindex="-1"></a><span class="co">#&gt; fx -&gt; fy       0.100</span></span>
<span id="cb15-43"><a href="#cb15-43" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-44"><a href="#cb15-44" tabindex="-1"></a><span class="co">#&gt;  - The &#39;ind&#39; column shows the indirect effect(s).</span></span>
<span id="cb15-45"><a href="#cb15-45" tabindex="-1"></a><span class="co">#&gt;  </span></span>
<span id="cb15-46"><a href="#cb15-46" tabindex="-1"></a><span class="co">#&gt; ==== Population Reliability ====</span></span>
<span id="cb15-47"><a href="#cb15-47" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-48"><a href="#cb15-48" tabindex="-1"></a><span class="co">#&gt;   fy  fm  fx</span></span>
<span id="cb15-49"><a href="#cb15-49" tabindex="-1"></a><span class="co">#&gt;  0.7 0.6 0.5</span></span>
<span id="cb15-50"><a href="#cb15-50" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-51"><a href="#cb15-51" tabindex="-1"></a><span class="co">#&gt; == Population Standardized Loadings ==</span></span>
<span id="cb15-52"><a href="#cb15-52" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-53"><a href="#cb15-53" tabindex="-1"></a><span class="co">#&gt;     fm    fx    fy</span></span>
<span id="cb15-54"><a href="#cb15-54" tabindex="-1"></a><span class="co">#&gt;  0.661 0.522 0.408</span></span>
<span id="cb15-55"><a href="#cb15-55" tabindex="-1"></a><span class="co">#&gt; ======================= Data Information =======================</span></span>
<span id="cb15-56"><a href="#cb15-56" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-57"><a href="#cb15-57" tabindex="-1"></a><span class="co">#&gt; Number of Replications:  400 </span></span>
<span id="cb15-58"><a href="#cb15-58" tabindex="-1"></a><span class="co">#&gt; Sample Sizes:  150 </span></span>
<span id="cb15-59"><a href="#cb15-59" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-60"><a href="#cb15-60" tabindex="-1"></a><span class="co">#&gt; Call print with &#39;data_long = TRUE&#39; for further information.</span></span>
<span id="cb15-61"><a href="#cb15-61" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-62"><a href="#cb15-62" tabindex="-1"></a><span class="co">#&gt; ==================== Extra Element(s) Found ====================</span></span>
<span id="cb15-63"><a href="#cb15-63" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-64"><a href="#cb15-64" tabindex="-1"></a><span class="co">#&gt; - fit</span></span>
<span id="cb15-65"><a href="#cb15-65" tabindex="-1"></a><span class="co">#&gt; - mc_out</span></span>
<span id="cb15-66"><a href="#cb15-66" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-67"><a href="#cb15-67" tabindex="-1"></a><span class="co">#&gt; === Element(s) of the First Dataset ===</span></span>
<span id="cb15-68"><a href="#cb15-68" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-69"><a href="#cb15-69" tabindex="-1"></a><span class="co">#&gt; ============ &lt;fit&gt; ============</span></span>
<span id="cb15-70"><a href="#cb15-70" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-71"><a href="#cb15-71" tabindex="-1"></a><span class="co">#&gt; lavaan 0.6-19 ended normally after 38 iterations</span></span>
<span id="cb15-72"><a href="#cb15-72" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-73"><a href="#cb15-73" tabindex="-1"></a><span class="co">#&gt;   Estimator                                         ML</span></span>
<span id="cb15-74"><a href="#cb15-74" tabindex="-1"></a><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span id="cb15-75"><a href="#cb15-75" tabindex="-1"></a><span class="co">#&gt;   Number of model parameters                        27</span></span>
<span id="cb15-76"><a href="#cb15-76" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-77"><a href="#cb15-77" tabindex="-1"></a><span class="co">#&gt;   Number of observations                           150</span></span>
<span id="cb15-78"><a href="#cb15-78" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-79"><a href="#cb15-79" tabindex="-1"></a><span class="co">#&gt; Model Test User Model:</span></span>
<span id="cb15-80"><a href="#cb15-80" tabindex="-1"></a><span class="co">#&gt;                                                       </span></span>
<span id="cb15-81"><a href="#cb15-81" tabindex="-1"></a><span class="co">#&gt;   Test statistic                                69.181</span></span>
<span id="cb15-82"><a href="#cb15-82" tabindex="-1"></a><span class="co">#&gt;   Degrees of freedom                                51</span></span>
<span id="cb15-83"><a href="#cb15-83" tabindex="-1"></a><span class="co">#&gt;   P-value (Chi-square)                           0.046</span></span>
<span id="cb15-84"><a href="#cb15-84" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-85"><a href="#cb15-85" tabindex="-1"></a><span class="co">#&gt; =========== &lt;mc_out&gt; ===========</span></span>
<span id="cb15-86"><a href="#cb15-86" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-87"><a href="#cb15-87" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-88"><a href="#cb15-88" tabindex="-1"></a><span class="co">#&gt; == A &#39;mc_out&#39; class object ==</span></span>
<span id="cb15-89"><a href="#cb15-89" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-90"><a href="#cb15-90" tabindex="-1"></a><span class="co">#&gt; Number of Monte Carlo replications: 2000 </span></span>
<span id="cb15-91"><a href="#cb15-91" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-92"><a href="#cb15-92" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-93"><a href="#cb15-93" tabindex="-1"></a><span class="co">#&gt; ====================== Test(s) Conducted ======================</span></span>
<span id="cb15-94"><a href="#cb15-94" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-95"><a href="#cb15-95" tabindex="-1"></a><span class="co">#&gt; - test_indirect: fx-&gt;fm-&gt;fy</span></span>
<span id="cb15-96"><a href="#cb15-96" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-97"><a href="#cb15-97" tabindex="-1"></a><span class="co">#&gt; Call print() and set &#39;test_long = TRUE&#39; for a detailed report.</span></span></code></pre></div>
</div>
<div id="compute-the-power" class="section level2">
<h2>Compute the Power</h2>
<p>The power estimate is simply the proportion of significant results,
the <em>rejection</em> <em>rate</em>, because the null hypothesis is
false. The rejection rate can be retrieved by
<code>rejection_rates()</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>out_power <span class="ot">&lt;-</span> <span class="fu">rejection_rates</span>(out)</span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>out_power</span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a><span class="co">#&gt; [test]: test_indirect: fx-&gt;fm-&gt;fy </span></span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a><span class="co">#&gt; [test_label]: Test </span></span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a><span class="co">#&gt;     est   p.v reject r.cilo r.cihi</span></span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a><span class="co">#&gt; 1 0.336 1.000  0.492  0.444  0.541</span></span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a><span class="co">#&gt; Notes:</span></span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a><span class="co">#&gt; - p.v: The proportion of valid replications.</span></span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a><span class="co">#&gt; - est: The mean of the estimates in a test across replications.</span></span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a><span class="co">#&gt; - reject: The proportion of &#39;significant&#39; replications, that is, the</span></span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a><span class="co">#&gt;   rejection rate. If the null hypothesis is true, this is the Type I</span></span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a><span class="co">#&gt;   error rate. If the null hypothesis is false, this is the power.</span></span>
<span id="cb16-13"><a href="#cb16-13" tabindex="-1"></a><span class="co">#&gt; - r.cilo,r.cihi: The confidence interval of the rejection rate, based</span></span>
<span id="cb16-14"><a href="#cb16-14" tabindex="-1"></a><span class="co">#&gt;   on normal approximation.</span></span>
<span id="cb16-15"><a href="#cb16-15" tabindex="-1"></a><span class="co">#&gt; - Refer to the tests for the meanings of other columns.</span></span></code></pre></div>
<p>In the example above, the estimated power of the test of the indirect
effect, conducted by Monte Carlo confidence interval, is 0.492, under
the column <code>reject</code>.</p>
<p><code>p.v</code> is the proportion of valid results across
replications. <code>1.000</code> means that the test conducted normally
in all replications.</p>
<p>By default, the 95% confidence interval of the rejection rate (power)
based on normal approximation is also printed, under the column
<code>r.cilo</code> and <code>r.cihi</code>. In this example, the 95%
confidence interval is [0.444; 0.541].</p>
</div>
</div>
<div id="new_n" class="section level1">
<h1>Repeat a Simulation With A Different Sample Size</h1>
<p>The function <code>power4test()</code> also supports <em>redoing</em>
an analysis using a new value for the sample size (or population effect
sizes set to <code>pop_es</code>). Simply</p>
<ul>
<li><p>set the output of <code>power4test</code> as the first argument,
and</p></li>
<li><p>set the <em>new value</em> for <code>n</code>.</p></li>
</ul>
<p>For example, we can repeat the simulation for the test of indirect
effect, but for a smaller sample size of 200. We simply call
<code>power4test()</code> again, set the previous output
(<code>out</code> in the example above) as the first argument, and set
<code>n</code> to a new value (200 in this example):</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>out_new_n <span class="ot">&lt;-</span> <span class="fu">power4test</span>(out,</span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>                        <span class="at">n =</span> <span class="dv">200</span>)</span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>out_new_n</span></code></pre></div>
<p>This is the estimated power when the sample size is 200.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>out_new_n_reject <span class="ot">&lt;-</span> <span class="fu">rejection_rates</span>(out_new_n)</span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>out_new_n_reject</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a><span class="co">#&gt; [test]: test_indirect: fx-&gt;fm-&gt;fy </span></span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a><span class="co">#&gt; [test_label]: Test </span></span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a><span class="co">#&gt;     est   p.v reject r.cilo r.cihi</span></span>
<span id="cb18-6"><a href="#cb18-6" tabindex="-1"></a><span class="co">#&gt; 1 0.352 1.000  0.815  0.777  0.853</span></span>
<span id="cb18-7"><a href="#cb18-7" tabindex="-1"></a><span class="co">#&gt; Notes:</span></span>
<span id="cb18-8"><a href="#cb18-8" tabindex="-1"></a><span class="co">#&gt; - p.v: The proportion of valid replications.</span></span>
<span id="cb18-9"><a href="#cb18-9" tabindex="-1"></a><span class="co">#&gt; - est: The mean of the estimates in a test across replications.</span></span>
<span id="cb18-10"><a href="#cb18-10" tabindex="-1"></a><span class="co">#&gt; - reject: The proportion of &#39;significant&#39; replications, that is, the</span></span>
<span id="cb18-11"><a href="#cb18-11" tabindex="-1"></a><span class="co">#&gt;   rejection rate. If the null hypothesis is true, this is the Type I</span></span>
<span id="cb18-12"><a href="#cb18-12" tabindex="-1"></a><span class="co">#&gt;   error rate. If the null hypothesis is false, this is the power.</span></span>
<span id="cb18-13"><a href="#cb18-13" tabindex="-1"></a><span class="co">#&gt; - r.cilo,r.cihi: The confidence interval of the rejection rate, based</span></span>
<span id="cb18-14"><a href="#cb18-14" tabindex="-1"></a><span class="co">#&gt;   on normal approximation.</span></span>
<span id="cb18-15"><a href="#cb18-15" tabindex="-1"></a><span class="co">#&gt; - Refer to the tests for the meanings of other columns.</span></span></code></pre></div>
<p>The estimated power is 0.815, 95% confidence interval [0.777; 0.853],
when the sample size is 200.</p>
<p>This technique can be repeated to find the required sample size for a
target power.</p>
</div>
<div id="repeat-a-simulation-with-different-numbers-of-indicators-or-reliability" class="section level1">
<h1>Repeat a Simulation With Different Numbers of Indicators or
Reliability</h1>
<p>We can also redo an analysis using a new value for reliability. For
example, we may want to see whether we can have a higher power if we use
more reliable scales.</p>
<p>As in the previous example, we just call <code>power4test()</code>
one the original output, but set <code>reliability</code> to a new
vector.</p>
<p>Assume that we want to know the power for the same scenario, but with
all scales having a population reliability of .80:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>out_new_rel <span class="ot">&lt;-</span> <span class="fu">power4test</span>(out,</span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a>                          <span class="at">reliability =</span> <span class="fu">c</span>(<span class="at">fx =</span> .<span class="dv">80</span>,</span>
<span id="cb19-3"><a href="#cb19-3" tabindex="-1"></a>                                          <span class="at">fm =</span> .<span class="dv">80</span>,</span>
<span id="cb19-4"><a href="#cb19-4" tabindex="-1"></a>                                          <span class="at">fy =</span> .<span class="dv">80</span>))</span>
<span id="cb19-5"><a href="#cb19-5" tabindex="-1"></a>out_new_rel</span></code></pre></div>
<p>This is the estimated power with higher population reliability:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a>out_new_rel_reject <span class="ot">&lt;-</span> <span class="fu">rejection_rates</span>(out_new_rel)</span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>out_new_rel_reject</span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a><span class="co">#&gt; [test]: test_indirect: fx-&gt;fm-&gt;fy </span></span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a><span class="co">#&gt; [test_label]: Test </span></span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a><span class="co">#&gt;     est   p.v reject r.cilo r.cihi</span></span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a><span class="co">#&gt; 1 0.235 1.000  0.985  0.973  0.997</span></span>
<span id="cb20-7"><a href="#cb20-7" tabindex="-1"></a><span class="co">#&gt; Notes:</span></span>
<span id="cb20-8"><a href="#cb20-8" tabindex="-1"></a><span class="co">#&gt; - p.v: The proportion of valid replications.</span></span>
<span id="cb20-9"><a href="#cb20-9" tabindex="-1"></a><span class="co">#&gt; - est: The mean of the estimates in a test across replications.</span></span>
<span id="cb20-10"><a href="#cb20-10" tabindex="-1"></a><span class="co">#&gt; - reject: The proportion of &#39;significant&#39; replications, that is, the</span></span>
<span id="cb20-11"><a href="#cb20-11" tabindex="-1"></a><span class="co">#&gt;   rejection rate. If the null hypothesis is true, this is the Type I</span></span>
<span id="cb20-12"><a href="#cb20-12" tabindex="-1"></a><span class="co">#&gt;   error rate. If the null hypothesis is false, this is the power.</span></span>
<span id="cb20-13"><a href="#cb20-13" tabindex="-1"></a><span class="co">#&gt; - r.cilo,r.cihi: The confidence interval of the rejection rate, based</span></span>
<span id="cb20-14"><a href="#cb20-14" tabindex="-1"></a><span class="co">#&gt;   on normal approximation.</span></span>
<span id="cb20-15"><a href="#cb20-15" tabindex="-1"></a><span class="co">#&gt; - Refer to the tests for the meanings of other columns.</span></span></code></pre></div>
<p>The estimated power is 0.985, 95% confidence interval [0.973; 0.997],
much higher than the original scenario.</p>
</div>
<div id="find-the-sample-size-with-desired-power" class="section level1">
<h1>Find the Sample Size With Desired Power</h1>
<p>There are several more efficient ways to find the sample size with
the desired power.</p>
<div id="using-n_region_from_power" class="section level2">
<h2>Using <code>n_region_from_power()</code></h2>
<p>The function <code>n_region_from_power()</code> can be used to find
the <em>region</em> of sample sizes likely to have the desired power. If
the default settings are to be used, then it can be called directly on
the output of <code>power4test()</code>:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a>out2_region <span class="ot">&lt;-</span> <span class="fu">n_region_from_power</span>(out2,</span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>                                   <span class="at">seed =</span> <span class="dv">2345</span>)</span></code></pre></div>
<p>This is the recommended way for sample size planning, when there is
no predetermined range of sample sizes.</p>
<p>See <a href="https://sfcheung.github.io/power4mome/articles/">the
templates</a> for examples on using <code>n_region_from_power()</code>
for common models.</p>
</div>
<div id="using-power4test_by_n" class="section level2">
<h2>Using <code>power4test_by_n()</code></h2>
<p>First, the function <code>power4test_by_n()</code> can be used To
estimate the power for a sequence of sample sizes. For example, suppose
we do not know that the power is about .80 with a sample size of 200. We
can estimate the power in the mediation model above for these sample
sizes: 175, 200, 225, 250.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>out_several_ns <span class="ot">&lt;-</span> <span class="fu">power4test_by_n</span>(out,</span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>                                  <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">175</span>, <span class="dv">200</span>, <span class="dv">225</span>, <span class="dv">250</span>),</span>
<span id="cb22-3"><a href="#cb22-3" tabindex="-1"></a>                                  <span class="at">by_seed =</span> <span class="dv">4567</span>)</span></code></pre></div>
<p>The first argument is the output of <code>power4test()</code> for an
arbitrary sample size.</p>
<p>The argument <code>n</code> is a numeric vector of sample sizes to
examine. For each <code>n</code>, <code>nrep</code> datasets will be
generated. Although there is no limit on the number of sample sizes to
try, it is recommended to restrict the number of sample sizes to 5 or
less.</p>
<p>The argument <code>by_seed</code>, if set to an integer, try to make
the results reproducible.</p>
<p>The call will take some time to run because it is equivalent to
calling <code>power4test()</code> once for each sample size.</p>
<p>The rejection rates for each sample size can be retrieved by
<code>rejection_rates()</code> too:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">rejection_rates</span>(out_several_ns)</span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a><span class="co">#&gt; [test]: test_indirect: fx-&gt;fm-&gt;fy </span></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a><span class="co">#&gt; [test_label]: Test </span></span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a><span class="co">#&gt;     n   est   p.v reject r.cilo r.cihi</span></span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a><span class="co">#&gt; 1 175 0.327 1.000  0.703  0.658  0.747</span></span>
<span id="cb23-6"><a href="#cb23-6" tabindex="-1"></a><span class="co">#&gt; 2 200 0.329 1.000  0.830  0.793  0.867</span></span>
<span id="cb23-7"><a href="#cb23-7" tabindex="-1"></a><span class="co">#&gt; 3 225 0.340 1.000  0.892  0.862  0.923</span></span>
<span id="cb23-8"><a href="#cb23-8" tabindex="-1"></a><span class="co">#&gt; 4 250 0.330 1.000  0.902  0.873  0.932</span></span>
<span id="cb23-9"><a href="#cb23-9" tabindex="-1"></a><span class="co">#&gt; Notes:</span></span>
<span id="cb23-10"><a href="#cb23-10" tabindex="-1"></a><span class="co">#&gt; - n: The sample size in a trial.</span></span>
<span id="cb23-11"><a href="#cb23-11" tabindex="-1"></a><span class="co">#&gt; - p.v: The proportion of valid replications.</span></span>
<span id="cb23-12"><a href="#cb23-12" tabindex="-1"></a><span class="co">#&gt; - est: The mean of the estimates in a test across replications.</span></span>
<span id="cb23-13"><a href="#cb23-13" tabindex="-1"></a><span class="co">#&gt; - reject: The proportion of &#39;significant&#39; replications, that is, the</span></span>
<span id="cb23-14"><a href="#cb23-14" tabindex="-1"></a><span class="co">#&gt;   rejection rate. If the null hypothesis is true, this is the Type I</span></span>
<span id="cb23-15"><a href="#cb23-15" tabindex="-1"></a><span class="co">#&gt;   error rate. If the null hypothesis is false, this is the power.</span></span>
<span id="cb23-16"><a href="#cb23-16" tabindex="-1"></a><span class="co">#&gt; - r.cilo,r.cihi: The confidence interval of the rejection rate, based</span></span>
<span id="cb23-17"><a href="#cb23-17" tabindex="-1"></a><span class="co">#&gt;   on normal approximation.</span></span>
<span id="cb23-18"><a href="#cb23-18" tabindex="-1"></a><span class="co">#&gt; - Refer to the tests for the meanings of other columns.</span></span></code></pre></div>
<p>The results show that, to have a power of about .800 to detect the
mediation effect, a sample size of about 200 is needed.</p>
<p>This approach is used when the range of sample sizes has already been
decided and the levels of power are needed to determine the final sample
size.</p>
<p>Please refer to the help page of <code>power4test_by_n()</code> for
other examples.</p>
</div>
<div id="using-x_from_power" class="section level2">
<h2>Using <code>x_from_power()</code></h2>
<p>The function <code>x_from_power()</code> can be used to
systematically search within an interval the sample size with the target
power. This takes longer to run but, instead of manually trying
different sample size, this function do the search automatically.</p>
<p>This approach can be used when the goal is to find the probable
minimum or maximum sample size with the desired level of power. The
first approach, using <code>n_region_from_power()</code>, simply uses
this approach twice to find the region of sample sizes.</p>
<p>See <a href="https://sfcheung.github.io/power4mome/articles/x_from_power_for_n.html">this
article</a> for an illustration of how to use
<code>x_from_power()</code>.</p>
</div>
</div>
<div id="other-scenarios" class="section level1">
<h1>Other Scenarios</h1>
<p>For other scenarios, such as moderation and moderated mediation,
please refer to <code>vignette(&quot;power4mome&quot;)</code>.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0" line-spacing="2">
<div id="ref-cheung_manymome_2024" class="csl-entry">
Cheung, S. F., &amp; Cheung, S.-H. (2024). <em>Manymome</em>:
<span>An</span> <span>R</span> package for computing the indirect
effects, conditional effects, and conditional indirect effects,
standardized or unstandardized, and their bootstrap confidence
intervals, in many (though not all) models. <em>Behavior Research
Methods</em>, <em>56</em>(5), 4862–4882. <a href="https://doi.org/10.3758/s13428-023-02224-z">https://doi.org/10.3758/s13428-023-02224-z</a>
</div>
</div>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p> Users can specify the values directly if necessary.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>The functions used are
<code>parallel::clusterSetRNGStream()</code> for parallel processing,
and <code>set.seed()</code> for serial processing.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>They are implemented by <code>manymome::do_mc()</code>
and <code>manymome::do_boot()</code>, respectively.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>The test is implemented by
<code>manymome::indirect()</code>.<a href="#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>The number of cores is determined automatically but can
be set directly by the <code>ncores</code> argument.<a href="#fnref5" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
